# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e4182dcb429ee6a939ac89c8911dc1e1e660ca53663ddf6ffd159fe70bf0ad748ed83524d7e9c1d429c2e739c04e27aee5f9ae3aab35172e770f41f338740d

test:
  secret_key_base: a7565ccdee95c03e0eb84eec8d0bf9549c95d50c930a479db364cb2508b07a93b506439a1d25e50c30c8d5f2e5152c6d0ad353ecfebf71b05f6664c233963de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
